<?php
$headTitle = 'Tutorial';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<div><?= $this->escapeHtml($this->greeting) ?></div>
<p><a href="/sample">Sample</a></p>
<form action="/tutorial" method="post">
    <input type="text" name="value">
    <button>Submit</button>
</form>
<hr>
<p><a href="/article">Article page</a></p>
<hr>
<p><a href="/product">Product page</a></p>