<?php
$headTitle = 'Article';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<p><a href="/article/add/15" class="btn btn-default">Add Article</a></p> <!--For method-->
<!--<p><a href="<?/*= $this->url('article', ['action' => 'add', 'id' => 10]) */?>">Add Article</a></p>--> <!--For segment-->
<!--<p><a href="/article/add/20">Add Article</a></p>--> <!--For regex-->
