<?php
$headTitle = 'Product';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<br>
<div><a href="/product/add/14" class="btn btn-default">Add product</a></div>
<p>
<?php
    echo $this->flashMessenger()->render('success', ['success-message']);
    echo $this->flashMessenger()->render('error',   ['error-message']);
?>
</p>
