<?php
$headTitle = 'Home';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<?php
    echo $this->flashMessenger()->render('success', ['success-message']);
    echo $this->flashMessenger()->render('error',   ['error-message']);
?>
<div><?= $this->escapeHtml($this->url) ?></div>
<div><?= $this->escapeHtml($this->date) ?></div>
