<?php

/*$str = ' <p>Hello world</p> ';

$stripTags  = new \Zend\Filter\StripTags();
$stringTrim = new \Zend\Filter\StringTrim();

$filterChain = new \Zend\Filter\FilterChain();
$filterChain->attach($stripTags)
            ->attach($stringTrim);

$str = $filterChain->filter($str);

var_dump($str);*/

/*$str = 'Hello world';

$stringLength = new Zend\Validator\StringLength(['min' => 1, 'max' => 5]);
$stringLength->setMessages([
    Zend\Validator\StringLength::TOO_SHORT => 'Too short',
    Zend\Validator\StringLength::TOO_LONG  => 'Too long',
]);

$alpha = new \Zend\I18n\Validator\Alpha();
$alpha->setMessages([
   Zend\I18n\Validator\Alpha::NOT_ALPHA => 'Not alpha',
]);

$validatorChain = new \Zend\Validator\ValidatorChain();
$validatorChain->attach($stringLength)
               ->attach($alpha);

if ($validatorChain->isValid($str)) {
    echo "Ok";
} else {
    foreach ($validatorChain->getMessages() as $message) {
        echo "<div>{$message}</div>";
    }
}*/

$value = 105;

$float = new \Tutorial\Validator\FloatValidator();

if ($float->isValid($value)) {
    echo 'Ok';
} else {
    foreach ($float->getMessages() as $message) {
        echo "<div>{$message}</div>";
    }
}

?>








<?php
$headTitle = 'Home';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<?php
    echo $this->flashMessenger()->render('success', ['success-message']);
    echo $this->flashMessenger()->render('error',   ['error-message']);
?>
<div><?= $this->escapeHtml($this->url) ?></div>
<div><?= $this->escapeHtml($this->date) ?></div>
<hr>
<p><a href="/download">Download</a></p>
<hr>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3048.663108235856!2d44.51459665062555!3d40.17205397929327!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x406abcf5dce61905%3A0x5b1b85523b3f82de!2z0KHQvtCx0L7RgCDQodCy0Y_RgtC-0LPQviDQk9GA0LjQs9C-0YDQuNGPINCf0YDQvtGB0LLQtdGC0LjRgtC10LvRjw!5e0!3m2!1sru!2sru!4v1499084822535" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
<hr>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3048.663108235856!2d44.51459665062555!3d40.17205397929327!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x406abcf5dce61905%3A0x5b1b85523b3f82de!2z0KHQvtCx0L7RgCDQodCy0Y_RgtC-0LPQviDQk9GA0LjQs9C-0YDQuNGPINCf0YDQvtGB0LLQtdGC0LjRgtC10LvRjw!5e0!3m2!1sru!2sru!4v1499084822535" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>